version: '3.8'

services:
  robotics-twin:
    build:
      context: ./robotics-digital-twin
      dockerfile: Dockerfile
    container_name: robotics_digital_twin_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  pipeline-inspector:
    build:
      context: ./pipeline-vision-inspector
      dockerfile: Dockerfile
    container_name: pipeline_vision_inspector_app
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
