"""
src/core/cmm_exporter.py
Translates extracted ASME Y14.5 CAD characteristics and Feature Control Frames
into standard DMIS (Dimensional Measuring Interface Standard) 5.2 / 5.3 inspection routines.
"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class CMMMeasurementFeature:
    feature_id: str          # e.g., 'FCF-01', 'DIM-01'
    feature_type: str        # 'PLANE', 'CYLINDER', 'CIRCLE', 'DISTANCE'
    nominal_xyz: tuple
    approach_vector_ijk: tuple
    tolerance: float
    tolerance_type: str      # 'FLAT', 'POS', 'DIST', 'DIAM'
    datums: List[str]


class DMISRoutineExporter:
    def __init__(self, part_name: str = "STEPPED_FLANGE", unit: str = "MM"):
        self.part_name = part_name
        self.unit = unit

    def export_dmis(self, features: List[CMMMeasurementFeature]) -> str:
        lines = [
            "$$ =================================================================",
            f"$$ DMIS 5.2 AUTOMATED INSPECTION ROUTINE: {self.part_name}",
            "$$ GENERATED BY INDUSTRIAL AI ASME Y14.5 INSPECTION MICROSERVICE",
            "$$ =================================================================",
            "DMISMN/'" + self.part_name + "'",
            f"UNITS/{self.unit},ANGDEC",
            "MODE/AUTO,PROG,MAN",
            "SNSET/APPRCH,5.000",
            "SNSET/RETRCT,5.000",
            "SNSET/SEARCH,10.000",
            "FEDRAT/MESVEL,SCNVEL,10.0000",
            "",
            "$$ --- DATUM ALIGNMENT SETUP ---",
            "F(DATUM_A)=FEAT/PLANE,CART,290.0000,600.0000,0.0000,0.0000,0.0000,1.0000",
            "MEAS/PLANE,F(DATUM_A),4",
            "  PTMEAS/CART,220.0000,580.0000,0.0000,0.0000,0.0000,1.0000",
            "  PTMEAS/CART,220.0000,620.0000,0.0000,0.0000,0.0000,1.0000",
            "  PTMEAS/CART,360.0000,580.0000,0.0000,0.0000,0.0000,1.0000",
            "  PTMEAS/CART,360.0000,620.0000,0.0000,0.0000,0.0000,1.0000",
            "ENDMES",
            "DATDEF/FA(DATUM_A),DAT(A)",
            "",
        ]

        # Generate measurement blocks per feature
        for feat in features:
            f_label = feat.feature_id.replace("-", "_")
            x, y, z = feat.nominal_xyz
            i, j, k = feat.approach_vector_ijk

            if feat.tolerance_type == "FLAT":
                lines.extend([
                    f"$$ --- MEASURE {feat.feature_id} (FLATNESS) ---",
                    f"F({f_label})=FEAT/PLANE,CART,{x:.4f},{y:.4f},{z:.4f},{i:.4f},{j:.4f},{k:.4f}",
                    f"MEAS/PLANE,F({f_label}),4",
                    f"  PTMEAS/CART,{x - 20:.4f},{y:.4f},{z:.4f},{i:.4f},{j:.4f},{k:.4f}",
                    f"  PTMEAS/CART,{x + 20:.4f},{y:.4f},{z:.4f},{i:.4f},{j:.4f},{k:.4f}",
                    f"  PTMEAS/CART,{x:.4f},{y - 20:.4f},{z:.4f},{i:.4f},{j:.4f},{k:.4f}",
                    f"  PTMEAS/CART,{x:.4f},{y + 20:.4f},{z:.4f},{i:.4f},{j:.4f},{k:.4f}",
                    "ENDMES",
                    f"T(T_{f_label})=TOL/FLAT,{feat.tolerance:.4f}",
                    f"OUTPUT/FA({f_label}),TA(T_{f_label})",
                    "",
                ])
            elif feat.tolerance_type == "POS":
                datum_str = ",".join([f"DAT({d})" for d in feat.datums]) if feat.datums else "DAT(A)"
                lines.extend([
                    f"$$ --- MEASURE {feat.feature_id} (POSITION MMC) ---",
                    f"F({f_label})=FEAT/CIRCLE,INNER,CART,{x:.4f},{y:.4f},{z:.4f},{i:.4f},{j:.4f},{k:.4f},320.0000",
                    f"MEAS/CIRCLE,F({f_label}),4",
                    f"  PTMEAS/CART,{x - 160:.4f},{y:.4f},{z:.4f},1.0000,0.0000,0.0000",
                    f"  PTMEAS/CART,{x + 160:.4f},{y:.4f},{z:.4f},-1.0000,0.0000,0.0000",
                    f"  PTMEAS/CART,{x:.4f},{y - 160:.4f},{z:.4f},0.0000,1.0000,0.0000",
                    f"  PTMEAS/CART,{x:.4f},{y + 160:.4f},{z:.4f},0.0000,-1.0000,0.0000",
                    "ENDMES",
                    f"T(T_{f_label})=TOL/POS,DIAM,{feat.tolerance:.4f},MMC,{datum_str}",
                    f"OUTPUT/FA({f_label}),TA(T_{f_label})",
                    "",
                ])
            else:
                lines.extend([
                    f"$$ --- MEASURE {feat.feature_id} (LINEAR DISTANCE) ---",
                    f"T(T_{f_label})=TOL/DIST,NOMIN,{x:.4f},-{feat.tolerance:.4f},{feat.tolerance:.4f}",
                    f"OUTPUT/FA({f_label}),TA(T_{f_label})",
                    "",
                ])

        lines.append("ENDFIL")
        return "\n".join(lines)
